### ISSUE TITLE
Circular reference error with libimobiledevice while building

### ISSUE THREAD

**Issue by fwd079** [libimobiledevice/usbmuxd#71] opened 2017-06-17 19:36 UTC
Hi, I downloaded git repositories for ifuse, libusbmuxd and libimobiledevice.
ifuse built successfully.

But for both libusbmuxd and libimobiledevice, the autogen.sh fails, complaining the other bit is not there. So you cannot run autogen.sh for either libusbmuxd or libimobiledevice.

Please can someone guide me how to build these? Thanks.

OS: Ubuntu 16.04 64 bit

**Comment by nikias** [comment] 2017-06-17 19:50
Duplicate of https://github.com/libimobiledevice/libimobiledevice/issues/518

**Closed by nikias** 2017-06-17 19:50 UTC
