### ISSUE TITLE
Error pairing with an iPhone 14

### ISSUE THREAD

**Issue by federicotorrielli** [libimobiledevice/usbmuxd#203] opened 2022-12-04 09:24 UTC
I compiled from source usbmuxd, libimobiledevice and libimobiledevice-glue. Everything is on HEAD and up to date, but the problem I had with `ERROR: Failed to read '/var/lib/lockdown/00008110-001C20223E29401E.plist'` still remains.
When I plug my usb the "trust this pc" on the iPhone and PC flash and go at the speed of light, usbmuxd is killed and restarted every second because of this. Do you have any fixes?

**Comment by sancelot** [comment] 2022-12-13 08:25
Duplicate of https://github.com/libimobiledevice/usbmuxd/issues/154

**Closed** 2022-12-13 09:03 UTC
